[package]
name = "lists_types"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
thiserror = "1.0.25"
uuid = { version = "0.8.2", features = ["serde"] }
