[package]
name = "cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
promptly = "0.3.0"
reqwest = { version = "0.11.3", default_features = false , features = ["json", "rustls-tls"]}
rpassword = "5.0.1"
serde = { version = "1.0.126", features = ["derive"] }
structopt = "0.3.21"
tokio = { version = "1.7.1", features = ["full"] }
yansi = "0.5.0"
