[package]
name = "lists_cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lists_client = { path = "../client" }
color-eyre = "0.5.11"
promptly = "0.3.0"
rpassword = "5.0.1"
structopt = "0.3.21"
tokio = { version = "1.7.1", features = ["full"] }
yansi = "0.5.0"
