[package]
name = "kabalist_api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
jsonwebtoken = "7.2.0"
serde = "1.0.126"
kabalist_types = { path = "../types" }
uuid = { version = "1.1.2", features = ["serde"] }
serde_repr = "0.1.8"
axum = { version = "0.5", features = ["headers"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros"] }
figment = { version = "0.10.6", features = ["toml", "env"] }
color-eyre = "0.6.1"
tokio-stream = "0.1.9"
tera = "1.16.0"

[dependencies.utoipa]
git = "https://github.com/juhaku/utoipa"
rev = "baa3947"
features = ["uuid"]

[dependencies.utoipa-swagger-ui]
git = "https://github.com/juhaku/utoipa"
rev = "baa3947"
features = ["axum"]

[dependencies.sqlx]
version = "0.6.0"
features = ["postgres", "migrate", "runtime-tokio-rustls", "macros", "uuid", "offline"]
