[package]
name = "kabalist_api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["frontend"]
frontend = ["tower-http/fs"]

[dependencies]
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
serde = "1.0.126"
kabalist_types = { path = "../types", features = ["openapi"] }
uuid = { version = "1.1.2", features = ["serde"] }
serde_repr = "0.1.8"
axum = { version = "0.6", features = ["headers"] }
tracing = "0.1.35"
tracing-subscriber = "0.3.14"
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros"] }
figment = { version = "0.10.6", features = ["toml", "env"] }
color-eyre = "0.6.1"
tokio-stream = "0.1.9"
tera = "1.16.0"
tower-http = { version = "0.3.4", features = ["cors"] }
utoipa = { version = "3.0.2", features = ["uuid"] }
utoipa-swagger-ui = { version = "3.0.2", features = ["axum"] }
jwt-simple = "0.11"

[dependencies.sqlx]
version = "0.6.2"
features = ["postgres", "migrate", "runtime-tokio-rustls", "macros", "uuid", "offline"]
