[package]
name = "kabalist_api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
jsonwebtoken = "7.2.0"
rocket = {version = "0.5.0-rc.1", features = ["json", "uuid"]}
rocket_sync_db_pools = "0.1.0-rc.1"
serde = "1.0.126"
sqlx = { version = "0.5.5", features = ["postgres", "migrate", "runtime-tokio-rustls", "macros", "uuid"] }
kabalist_types = { path = "../types" }
uuid = { version = "0.8.2", features = ["serde"] }

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.1"
features = ["tera"]
