cookie_secret = "B50D8FB3A6DC3073259062EFFD03A283416A81ED3183C44DEE179AFF76C00B58FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
exp = 10000000000
listen_addr = "0.0.0.0"
port = 8080
database_url = "postgres://traxys:traxys@localhost/list"
frontend = "../web/dist"
#template_dir = "public"
oauth_issuer = "https://example.com/oauth2/openid/"
oauth_id = "oauth2 client id"
oauth_secret = "oauth2 client secret"
oauth_redirect = "http://<YOUR URL>/api/account/callback"
oauth_redirect_mobile = "http://<YOUR URL>/api/account/callback/mobile"
