jwt_secret = "B50D8FB3A6DC3073259062EFFD03A283416A81ED3183C44DEE179AFF76C00B58FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
exp = 10000000000
listen_addr = "0.0.0.0"
port = 80
database_url = "postgres://traxys:traxys@localhost/list"
frontend = "../web/dist"
#template_dir = "public"
oauth_issuer = "https://users.familleboyer.net/oauth2/openid/kabalist_test"
oauth_id = "kabalist_test"
oauth_secret = "VUxND3PydTrkNBr8NuuqaEqEqWBR0z3DWMwhc4GSEVrB2e4p"
oauth_redirect = "http://kb.maix.me/api/account/callback"
oauth_redirect_mobile = "http://kb.maix.me/api/account/callback/mobile"
